app_demo:
<<<<<<< HEAD
    resource: "@AppDemoBundle/Resources/config/routing.yml"
    prefix: /client
=======
    resource: "@AppDemoBundle/Controller/"
    type: annotation
    prefix: /client

>>>>>>> 8337af1a2aa1222ebc8cd71c0c11be9541d4a01b
users:
    type: rest
    resource: App\DemoBundle\Controller\UsersController

